AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Instance Template - Uses VPC outputs from vpc-template.yaml'

Parameters:
  VpcStackName:
    Type: String
    Description: Name of the VPC CloudFormation stack
    Default: vpc-1
  
  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t3.micro
      - t3.small
      - t3.medium
  
  SubnetType:
    Type: String
    Description: Deploy instance in public or private subnet
    Default: public
    AllowedValues:
      - public
      - private
  
  UseSSM:
    Type: String
    Description: Use SSM Session Manager instead of key-pair
    Default: 'true'
    AllowedValues:
      - 'true'
      - 'false'
  
  KeyPairName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair name (only used if UseSSM is false)
    Default: ''

Resources:
  # Get VPC outputs from the VPC stack
  PublicSubnetId:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://s3.amazonaws.com/cloudformation-templates/${VpcStackName}-outputs.yaml'
    Condition: UsePublicSubnet
  
  # EC2 Instance in Public Subnet
  PublicInstance:
    Type: AWS::EC2::Instance
    Condition: UsePublicSubnet
    Properties:
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 (update for your region)
      InstanceType: !Ref InstanceType
      SubnetId: !ImportValue
        Fn::Sub: '${VpcStackName}-Public-Subnet-ID'
      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: '${VpcStackName}-Public-SG-ID'
      IamInstanceProfile: !If
        - UseSSM
        - !ImportValue
          Fn::Sub: '${VpcStackName}-SSM-InstanceProfile-ARN'
        - !Ref AWS::NoValue
      KeyName: !If
        - UseKeyPair
        - !Ref KeyPairName
        - !Ref AWS::NoValue
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y amazon-ssm-agent
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent
      Tags:
        - Key: Name
          Value: !Sub '${VpcStackName}-Public-Instance'
        - Key: Type
          Value: Public
  
  # EC2 Instance in Private Subnet
  PrivateInstance:
    Type: AWS::EC2::Instance
    Condition: UsePrivateSubnet
    Properties:
      ImageId: ami-0c55b159cbfafe1f0  # Amazon Linux 2 (update for your region)
      InstanceType: !Ref InstanceType
      SubnetId: !ImportValue
        Fn::Sub: '${VpcStackName}-Private-Subnet-1-ID'
      SecurityGroupIds:
        - !ImportValue
          Fn::Sub: '${VpcStackName}-Private-SG-ID'
      IamInstanceProfile: !ImportValue
        Fn::Sub: '${VpcStackName}-SSM-InstanceProfile-ARN'
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y amazon-ssm-agent
          systemctl enable amazon-ssm-agent
          systemctl start amazon-ssm-agent
      Tags:
        - Key: Name
          Value: !Sub '${VpcStackName}-Private-Instance'
        - Key: Type
          Value: Private

Conditions:
  UsePublicSubnet: !Equals [!Ref SubnetType, 'public']
  UsePrivateSubnet: !Equals [!Ref SubnetType, 'private']
  UseSSM: !Equals [!Ref UseSSM, 'true']
  UseKeyPair: !And
    - !Equals [!Ref UseSSM, 'false']
    - !Not [!Equals [!Ref KeyPairName, '']]

Outputs:
  InstanceId:
    Description: EC2 Instance ID
    Value: !If
      - UsePublicSubnet
      - !Ref PublicInstance
      - !Ref PrivateInstance
  
  InstancePublicIP:
    Description: Public IP Address (only for public subnet instances)
    Value: !If
      - UsePublicSubnet
      - !GetAtt PublicInstance.PublicIp
      - 'N/A'
  
  SSMConnectCommand:
    Description: Command to connect via SSM Session Manager
    Value: !Sub
      - 'aws ssm start-session --target ${InstanceId} --region <region>'
      - InstanceId: !If
          - UsePublicSubnet
          - !Ref PublicInstance
          - !Ref PrivateInstance
